### PR TITLE
feat: datetime iso

### PR DESCRIPTION
**Pull request by Gounlaf**
* [x] make sure to always "parse" date as iso input if possible

### CODE REVIEW

**Comment by Gounlaf** [comment]
I didn't manage to run tests (even before my modifications).

**Comment by Tchekda** [comment]
Hello, 
We also want the current line to display the UTC TIme (per #19).
Is there anything missing from this PR that you would need help making it ready to be merged?

**Comment by karolkozer** [comment]
@Tchekda UTC feature has been done. That was difficult task cuz there were a lot of issues. Now, it is in beta/testing version.

**Comment by Tchekda** [comment]
> @Tchekda UTC feature has been done. That was difficult task cuz there were a lot of issues. Now, it is in beta/testing version.

Thank you very much, will be waiting for the public release it test it. 
Thank you very much

**Pull request closed without merging**
